### PR TITLE
Command handlers

### LINKED ISSUE #35: Change command handlers
`function (callable $stateResolver, Command $command): Events[]`

Pros:

- more explicit
- no loading of state / history events, when not needed

refers to https://github.com/prooph/micro/issues/34

### PR DESCRIPTION
**Pull request by prolic**
resolves https://github.com/prooph/micro/issues/35

- Command handler is now `function (callable $stateResolver, Command $command): Events[]`
- AggregateResult is removed
- AggregateDefinition is updated
- Kernel pipeline simplified
- Updated tests
- Updated example
- Snapshotting in batches

### CODE REVIEW

**Comment by prolic** [comment]
This also simplifies the code and removes a lot! :)

**Review by codeliner — APPROVED** [review]

**Comment by codeliner** [comment]
great, great, great. Looks really good with the stateResolver

**Comment by prolic** [comment]
See how registering works now, it checks for unique email address and if it is a new registration, no state / events are loaded at all!

**Comment by bweston92** [comment]
LGTM - room for `TypeError`s from state resolver that could be handled nicer, but that shouldn't ever reach production.

**Comment by prolic** [comment]
@bweston92 PR?

**Comment by bweston92** [comment]
@prolic will do if I think of a decent way :)

**Pull request merged**
