### PR TITLE
add id, compose and curry function

### PR DESCRIPTION
**Pull request by prolic**
This will be the base for a refactoring of micro, please review and leave your comments.

### CODE REVIEW

**Comment by bweston92** [comment]
LGTM - looks familiar to the slides on functional PHP :D

**Comment by sandrokeil** [comment]
It's nice, but do not forget the performance drawbacks. Every function call is expensive. Hopefully PHP can improve it in later releases.

**Comment by prolic** [comment]
I am working on another implementation. This is closed for now, but new PR
following soon.

**Comment by basz** [comment]
Looks great, but what does it? Theory...

**Comment by prolic** [comment]
@bweston92 @sandrokeil @bweston92 please be patient one more day... i am nearly finished with my `next` proposal (I tend not to use `final` here, as I am still exploring the functional programming world with PHP)

**Pull request closed without merging**
